### ISSUE TITLE
Problem with PMF [fit() method]

### ISSUE THREAD

**Issue by TheEdoardo93** [chyikwei/recommend#17]
Hi,
I'm a computer science student in Milan. My goal is to use this library in order to perform PMF on my ratings matrix.
The problem I encountered is the following: 
"File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py", line 62, in fit
    self.max_rating, self.min_rating)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/utils/validation.py", line 22, in check_ratings
    raise ValueError("max user_id >= %d", n_user)
ValueError: ('max user_id >= %d', 4)

My ratings matrix is like your ratings matrix in your examples (so, each user and item id start from 0, not from 1, so I don't have to set -1 for the id). One example of my ratings matrix is the following:

"[[0 0 1]
 [0 1 2]
 [0 2 1]
 [0 3 1]
 [0 4 0]
 [1 0 1]
 [1 1 0]
 [1 2 4]
 [1 3 4]
 [1 4 4]
 [2 0 1]
 [2 1 1]
 [2 2 0]
 [2 3 1]
 [2 4 1]
 [3 0 5]
 [3 1 4]
 [3 2 5]
 [3 3 5]
 [3 4 0]
 [4 0 3]
 [4 1 1]
 [4 2 0]
 [4 3 3]
 [4 4 3]]"

As you can see, max user id = 4 and also max item id = 4 (and both start from 0, not from 1).

When I call fit() method, my program stops giving me that error.
I don't know how to solve my problem. 
Can you give me a help?

Thanks.

**Comment by TheEdoardo93** [comment]
I solved this problem, but I have another "problem".
How can I obtain the latent features for an user or for an item?
My final goal is to obtain the latent features learned with PMF model. How can I do that?

Thanks a lot.

**Comment by chyikwei** [comment]
It is good to know you solved it. 
The features are stored in `user_features_` and `item_features_` attributes.
https://github.com/chyikwei/recommend/blob/master/recommend/pmf.py#L56-L57

**Comment by TheEdoardo93** [comment]
Thank you for writing back to me very fast.

I saw in the source code of the library that there are “user_features_" and “item_features” attributes of PMF class.
I've obtained these latent features. It is correct? In “x” and “y” Python variable, I can find the latent features for users and items? (see please 213-216 source code rows)
I attached you two images of my source code in Python which works (you can see in the console below in the second image what is the result obtained from launching my software).

Thanks a lot!

Edoardo Casiraghi
edoardo.casiraghi.93@gmail.com

**Comment by chyikwei** [comment]
Hi Edoardo,
I don't see any attachments. can you share your code in a gist?

**Comment by TheEdoardo93** [comment]
I re-send the two images in this e-mail.



Edoardo Casiraghi
edoardo.casiraghi.93@gmail.com

**Comment by TheEdoardo93** [comment]
https://gist.github.com/TheEdoardo93/7bce72c08ab4839a150034340634ecbd

 In “x” and “y” Python variable, can I find the latent features for users and items? (see 43-46 source code rows) - obviously of "number_of_features" dimensions

Thanks, best regards!

**Comment by chyikwei** [comment]
`user_features_` is a (n_user, n_feature) array. Each row represent the latent feature for 1 user (Ex. row 0 is the latent features for user 0 and so on.)

`item_features_` is the same.

**Comment by TheEdoardo93** [comment]
Thanks for the fast answer to my problem!
Have a good luck in your future, bye!

**Comment by chyikwei** [comment]
ok. close this now.
