### ISSUE TITLE
Problems with PMF

### ISSUE THREAD

**Issue by TheEdoardo93** [chyikwei/recommend#19]
Hi,
My professor and I have investigated deeply this library for applying PMF on a ratings matrix and we have encountered a problem during fit() method of PMF.
With 'ratings_matrix' we indicate the ratings matrix which we give as input to this library.

ratings_matrix = [[  9.00000000e+00   2.71600000e+03   4.00000000e+00]
 [  3.84100000e+03   3.50300000e+03   5.00000000e+00]
 [  2.89900000e+03   1.24600000e+03   5.00000000e+00]
 ..., 
 [  2.63700000e+03   1.26700000e+03   3.00000000e+00]
 [  2.83000000e+02   2.42000000e+03   1.00000000e+00]
 [  4.55100000e+03   1.64000000e+02   3.00000000e+00]]

When we call fit() method - pmf = PMF(n_user = number_of_users, n_item = number_of_items, n_feature = number_of_features, min_rating = min_rating_value, max_rating = max) - , with Numpy version 1.13.3, we encountered this problem (the following):
Traceback (most recent call last):
  File "/Users/edoardo/PycharmProjects/MasterThesisProject/Thesis.py", line 529, in <module>
    final_ratings_matrix_pmf = probabilistic_matrix_factorization_technique(ratings_matrix)
  File "/Users/edoardo/PycharmProjects/MasterThesisProject/Thesis.py", line 250, in probabilistic_matrix_factorization_technique
    pmf = PMF(n_user = number_of_users, n_item = number_of_items, n_feature = number_of_features, min_rating = min_rating_value, max_rating = max_rating_value, seed = initial_seed)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py", line 56, in __init__
    self.user_features_ = 0.1 * self.random_state.rand(n_user, n_feature)
  File "mtrand.pyx", line 1358, in mtrand.RandomState.rand
  File "mtrand.pyx", line 856, in mtrand.RandomState.random_sample
  File "mtrand.pyx", line 167, in mtrand.cont0_array
TypeError: 'numpy.float64' object cannot be interpreted as an index

When we call fit() method - , with Numpy version 1.11.0, we encountered this other problem (the following):
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py:56: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.user_features_ = 0.1 * self.random_state.rand(n_user, n_feature)
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py:57: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.item_features_ = 0.1 * self.random_state.rand(n_item, n_feature)
PMF training and testing phases
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py:70: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  u_feature_mom = np.zeros((self.n_user, self.n_feature))
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py:71: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  i_feature_mom = np.zeros((self.n_item, self.n_feature))
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py:73: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  u_feature_grads = np.zeros((self.n_user, self.n_feature))
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py:74: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  i_feature_grads = np.zeros((self.n_item, self.n_feature))
Traceback (most recent call last):
  File "/Users/edoardo/PycharmProjects/MasterThesisProject/Thesis.py", line 529, in <module>
    final_ratings_matrix_pmf = probabilistic_matrix_factorization_technique(ratings_matrix)
  File "/Users/edoardo/PycharmProjects/MasterThesisProject/Thesis.py", line 254, in probabilistic_matrix_factorization_technique
    pmf.fit(training_set, n_iters = evaluation_iterations)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/recommend/pmf.py", line 87, in fit
    data.take(0, axis=1), axis=0)
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

Have you ever encountered this type of problem? We don't know how to solve this problem!

Any help can be useful! Thanks a lot!

**Comment by chyikwei** [comment]
Can you check the type of `n_user` ( and `n_item`) and make sure they are `int`?

Numpy will raise error when you pass`float` number in rand() function. like this:

```python
>>> import numpy as np
>>> np.__version__
'1.13.1'
>>> from numpy.random import RandomState
>>> rs = RandomState(0)

>>> rs.rand(10)  # use int works
array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ,
        0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152])

>>> rs.rand(10.) # use float will rise error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1358, in mtrand.RandomState.rand (numpy/random/mtrand/mtrand.c:19746)
  File "mtrand.pyx", line 856, in mtrand.RandomState.random_sample (numpy/random/mtrand/mtrand.c:15541)
  File "mtrand.pyx", line 167, in mtrand.cont0_array (numpy/random/mtrand/mtrand.c:6141)
TypeError: 'float' object cannot be interpreted as an index
```

**Comment by TheEdoardo93** [comment]
That was the mistake!
Thanks a lot for your patience and help!
