### ISSUE TITLE
Parameter 'Lambda' in the ALS-WR Model

### ISSUE THREAD

**Issue by TheEdoardo93** [chyikwei/recommend#23]
Hi,
I've seen the implementation of the ALS-WR model provided in this library.
This model has got a parameter called 'lambda'. I've a question: can I set the 'lambda' parameter of the model and how? The 'lambda' parameter in the reference paper is the 'reg' parameter in this implementation, right? If wrong, how can I set the 'lambda' parameter?

Thanks for the answer!
Best regards.

**Comment by chyikwei** [comment]
yes. `lambda` in the paper is `reg` parameter in the model.
