### ISSUE TITLE
RuntimeWarning: overflow encountered in multiply

### ISSUE THREAD

**Issue by XiyangGu** [chyikwei/recommend#9]
Hi

I let eval_iters = 50, I encountered a problem(RuntimeWarning: overflow encountered in multiply). With the number of eval_iters' increase, I only want to have the minimized RMSE. But I don't know how to solve the problem.
Here is the question:
recommend-0.1.0-py2.7.egg/recommend/pmf.py:86: RuntimeWarning: overflow encountered in multiply
recommend-0.1.0-py2.7.egg/recommend/pmf.py:88: RuntimeWarning: overflow encountered in multiply
recommend-0.1.0-py2.7.egg/recommend/pmf.py:89: RuntimeWarning: overflow encountered in multiply
recommend-0.1.0-py2.7.egg/recommend/pmf.py:90: RuntimeWarning: overflow encountered in multiply
recommend-0.1.0-py2.7.egg/recommend/pmf.py:97: RuntimeWarning: invalid value encountered in add
recommend-0.1.0-py2.7.egg/recommend/pmf.py:104: RuntimeWarning: invalid value encountered in add
recommend-0.1.0-py2.7.egg/recommend/pmf.py:133: RuntimeWarning: invalid value encountered in greater
site-packages/recommend-0.1.0-py2.7.egg/recommend/pmf.py:136: RuntimeWarning: invalid value encountered in less
INFO: iter: 24, train RMSE: nan
INFO: iter: 25, train RMSE: nan
INFO: iter: 26, train RMSE: nan
INFO: iter: 27, train RMSE: nan ...

**Comment by chyikwei** [comment]
Hi,
I guess the algorithm is not converged and caused the overflow.
Is your training RMSE goes up in each iteration before iteration 24?
(In this case, you can try smaller `epsilon` parameter)

**Comment by XiyangGu** [comment]
Hey,
Thank you for your help! Much appreciated!
Yes. as you said, my training RMSE goes up before iteration 24.

INFO: iter: 18, train RMSE: 0.932518
INFO: iter: 19, train RMSE: 0.929127
INFO: iter: 20, train RMSE: 0.926401
INFO: iter: 21, train RMSE: 0.927020
INFO: iter: 22, train RMSE: 0.963811
INFO: iter: 23, train RMSE: 2.356980 

I also test epsilon parameter in BPMF, it works well.  \(^o^)/~

**Comment by chyikwei** [comment]
np. I'm glad it solved the problem. close this now.
